INSERT INTO Booking VALUES ('123456');

INSERT INTO Flight(FLIGHT_NUMBER , ARRIVAL_AIRPORT , ARRIVAL_DATE , DEPARTURE_AIRPORT, DEPARTURE_DATE ) VALUES   ('456', 'AA1', TO_DATE('2019/12/25', 'yyyy/mm/dd'), 'DA1', TO_DATE('2019/12/25', 'yyyy/mm/dd'));
INSERT INTO BOOKING_FLIGHT_LIST( BOOKING_LIST_BOOKING_ID, FLIGHT_LIST_FLIGHT_NUMBER) VALUES ('123456', '456');
INSERT INTO PASSENGER(PASSENGER_ID, EMAIL, FIRST_NAME, LAST_NAME, BOOKING_BOOKING_ID) VALUES ('567','madh@gmailcom','madhawa','gunasekara','123456');

INSERT INTO Flight(FLIGHT_NUMBER , ARRIVAL_AIRPORT , ARRIVAL_DATE , DEPARTURE_AIRPORT, DEPARTURE_DATE ) VALUES   ('113', 'AA2', TO_DATE('2019/12/27', 'yyyy/mm/dd'), 'DA2', TO_DATE('2019/12/28', 'yyyy/mm/dd'));
INSERT INTO BOOKING_FLIGHT_LIST( BOOKING_LIST_BOOKING_ID, FLIGHT_LIST_FLIGHT_NUMBER) VALUES ('123456', '113');
INSERT INTO PASSENGER(PASSENGER_ID, EMAIL, FIRST_NAME, LAST_NAME, BOOKING_BOOKING_ID) VALUES ('879','david@gmailcom','david','silva','123456');


INSERT INTO Booking VALUES ('765432');

INSERT INTO Flight(FLIGHT_NUMBER , ARRIVAL_AIRPORT , ARRIVAL_DATE , DEPARTURE_AIRPORT, DEPARTURE_DATE ) VALUES   ('897', 'AA3', TO_DATE('2019/12/25', 'yyyy/mm/dd'), 'DA3', TO_DATE('2019/12/20', 'yyyy/mm/dd'));
INSERT INTO BOOKING_FLIGHT_LIST( BOOKING_LIST_BOOKING_ID, FLIGHT_LIST_FLIGHT_NUMBER) VALUES ('765432', '897');
INSERT INTO PASSENGER(PASSENGER_ID, EMAIL, FIRST_NAME, LAST_NAME, BOOKING_BOOKING_ID) VALUES ('100','luvi@gmailcom','luvi','jesper','765432');